<nav class="bg-neutral-900 z-40 w-full">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="relative flex items-center justify-between py-2">
            <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
                <div class="flex-shrink-0 flex items-center">
                    <a href="/" ><img src="https://brand.lmwn.co.uk/logo.png" class="h-6 w-auto" alt="LMWN Logo"></a>
                </div>
                <div class="hidden sm:block sm:ml-6">
                    <div class="flex space-x-4">
                        <a href="/" class="text-neutral-300 hover:bg-neutral-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>